import {get_encoding} from "tiktoken"

function main(prompt) {
    // Defined the Tokenizer model
    const encodingTokenizer = get_encoding("o200k_base")
    
    // Encoding the sentence aka prompt given by the user
    const encodedText = encodingTokenizer.encode(prompt)

    // Decoding the encoded sentence aka prompt generated by the tokenizer
    const decodedText = new TextDecoder().decode(encodingTokenizer.decode(encodedText))

    console.log(`This is the prompt :: ${prompt}`);
    console.log(`This is how it is Encoded using a tokenizer :: ${encodedText}`);
    console.log(`This is how it is Decoded using the same tokenizer :: ${decodedText}`);
}

main("Hello,I am Rabi. It's nice to meet you.")

// This is the prompt :: Hello,I am Rabi. It's nice to meet you.
// This is how it is Encoded using a tokenizer :: 13225,75570,939,460,13177,13,7744,7403,316,4158,481,13
// This is how it is Decoded using the same tokenizer :: Hello,I am Rabi. It's nice to meet you.